[package]
name = "sevenkey-global-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
emojis = "0.6.4"
rosu-v2 = "0.10.0"
serde = "1.0.219"
serde_json = "1.0.140"
serenity = "0.12.4"
tokio = { version = "1.44.1", features = ["full"] }

[lib]
path = "src/lib.rs"
